export default {
  login: "Rakesh D R",
id: 65976124,
node_id: "MDQ6VXNlcjY1OTc2MTI0",
avatar_url: "https://avatars1.githubusercontent.com/u/65976124?v=4",
gravatar_id: "",
url: "https://api.github.com/users/rakeshdr543",
html_url: "https://github.com/rakeshdr543",
followers_url: "https://api.github.com/users/rakeshdr543/followers",
following_url: "https://api.github.com/users/rakeshdr543/following{/other_user}",
gists_url: "https://api.github.com/users/rakeshdr543/gists{/gist_id}",
starred_url: "https://api.github.com/users/rakeshdr543/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/rakeshdr543/subscriptions",
organizations_url: "https://api.github.com/users/rakeshdr543/orgs",
repos_url: "https://api.github.com/users/rakeshdr543/repos",
events_url: "https://api.github.com/users/rakeshdr543/events{/privacy}",
received_events_url: "https://api.github.com/users/rakeshdr543/received_events",
type: "User",
site_admin: false,
name: "Rakesh D R",
company: 'Coding',
blog: "",
location: 'Banglore',
email: null,
hireable: null,
bio: 'Coding awesome things ...',
twitter_username: 'rakesh',
public_repos: 19,
public_gists: 0,
followers: 15,
following: 11,
created_at: "2020-05-26T18:45:26Z",
updated_at: "2021-01-04T14:45:07Z"

};
